---
- hosts: all
  roles:
  - role: cask_package
    package_name: spectacle
  ## vms
  - role: cask_package
    package_name: virtualbox
  - role: cask_package
    package_name: vagrant
  ## cli tools
  - role: brew_package
    package_name: ack
  - role: brew_package
    package_name: bash-completion
  - role: brew_package
    package_name: the_silver_searcher
  - role: brew_package
    package_name: tmux
  - role: brew_package
    package_name: tree
  - role: brew_package
    package_name: wget
  ## Languages
  - role: brew_package
    package_name: ghc
  - role: brew_package
    package_name: go
  - role: brew_package
    package_name: sbt
